# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-12 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name=b'Name of Product')),
                ('image', models.ImageField(blank=True, upload_to=b'product_photos/', verbose_name=b'Image Path to Product')),
                ('description', models.TextField(blank=True, verbose_name=b'Description of Product')),
                ('price', models.FloatField(blank=True, verbose_name=b'Price of Product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
