# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-13 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180212_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='on_sale',
            field=models.BooleanField(default=False, verbose_name=b'Product on Sale'),
        ),
    ]
